# Generated by Django 5.0.7 on 2024-08-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='doctor_photos/')),
                ('qualification', models.CharField(max_length=255)),
                ('specialist_field', models.CharField(max_length=255)),
                ('documentation', models.FileField(upload_to='doctor_docs/')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
